# Generated by Django 3.1.1 on 2020-10-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_figura_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artbook',
            fields=[
                ('id_artbook', models.AutoField(db_column='id_artbook', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoArtbook', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id_manga', models.AutoField(db_column='id_manga', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('editorial', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoManga', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
        ),
    ]
