# Generated by Django 3.1.1 on 2020-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_artbook_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='nombre_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
