# Generated by Django 3.1.1 on 2020-10-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_manga_nombre_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbook',
            name='nombre_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artbook',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
