# Generated by Django 3.1.1 on 2020-10-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_auto_20201025_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(db_column='id_contacto', primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('asunto', models.CharField(blank=True, max_length=10, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='figura',
            name='codigof',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
