# Generated by Django 3.1.1 on 2020-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20201026_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbook',
            name='codigoA',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='codigoM',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
