# Generated by Django 3.1.1 on 2020-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20201028_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='artbook',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='figura',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='activo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
